#!/usr/bin/env bash
# Redirection

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP'
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
